-- class project: table for saving each ping
-- paste this whole thing into supabase sql editor and hit run

create table if not exists public.ping_logs (
  id bigint generated by default as identity primary key,
  url text not null,
  checked_at timestamptz not null,
  ok boolean not null,
  status_code integer,
  latency_ms integer not null,
  error text,
  created_at timestamptz not null default now()
);

-- makes lookups by url faster (i think??)
create index if not exists ping_logs_url_checked_at_idx
  on public.ping_logs (url, checked_at desc);

-- rls is required kinda, our node script uses secret key so it bypasses rls anyway
alter table public.ping_logs enable row level security;

-- optional policy for if you build a login page later idk
do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'ping_logs'
      and policyname = 'read ping logs'
  ) then
    create policy "read ping logs"
      on public.ping_logs
      for select
      to authenticated
      using (true);
  end if;
end $$;
